version: '3'

services:

  test-shell:    
    container_name: test-shell
    hostname: test-shell
    image: alpine:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/go/src/github.com/antonio-alexander/go-hello-world

  hello-world-cli:    
      container_name: hello-world-cli
      hostname: hello-world-cli
      image: hello-world-cli:latest
      # entrypoint: ["tail", "-f", "/dev/null"]
      build:
        context: ../
        dockerfile: ./cmd/cli/Dockerfile

  hello-world-rest:
    container_name: hello-world-rest
    hostname: hello-world-rest
    image: hello-world-rest:latest
    # entrypoint: ["tail", "-f", "/dev/null"]
    restart: "always"
    build:
      context: ../
      dockerfile: ./cmd/rest/Dockerfile
    ports:
      - "8080:8080"

  hello-world-rest-debug:
    container_name: hello-world-rest-debug
    hostname: hello-world-rest-debug
    image: hello-world-rest-debug:latest
    # entrypoint: ["tail", "-f", "/dev/null"]
    restart: "always"
    build:
      context: ../
      dockerfile: ./cmd/rest/Dockerfile.Debug
    ports:
      - "8081:8080"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - .:/go/src/github.com/antonio-alexander/go-hello-world
